<a href="https://colab.research.google.com/github/AbhishekAdi/first-repo/blob/main/Coupon_Acceptance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
file_path ="/content/drive/MyDrive/Ds_Data.csv"
df = pd.read_csv(file_path)
df.head(100)

,destination,passanger,weather,temperature,coupon,expiration,gender,age,maritalStatus,has_children,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Accept(Y/N?)
0,No Urgent Place,Alone,Sunny,55,Restaurant(<20),1d,Female,21,Unmarried partner,1,...,never,NaN,4~8,1~3,1,0,0,0,1,1
1,No Urgent Place,Friend(s),Sunny,80,Coffee House,2h,Female,21,Unmarried partner,1,...,never,NaN,4~8,1~3,1,0,0,0,1,0
2,No Urgent Place,Friend(s),Sunny,80,Carry out & Take away,2h,Female,21,Unmarried partner,1,...,never,NaN,4~8,1~3,1,1,0,0,1,1
3,No Urgent Place,Friend(s),Sunny,80,Coffee House,2h,Female,21,Unmarried partner,1,...,never,NaN,4~8,1~3,1,1,0,0,1,0
4,No Urgent Place,Friend(s),Sunny,80,Coffee House,1d,Female,21,Unmarried partner,1,...,never,NaN,4~8,1~3,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),1d,Male,21,Single,0,...,less1,1~3,less1,1~3,1,1,0,0,1,1
96,No Urgent Place,Friend(s),Sunny,80,Coffee House,2h,Male,21,Single,0,...,less1,1~3,less1,1~3,1,0,0,0,1,1
97,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),2h,Male,21,Single,0,...,less1,1~3,less1,1~3,1,1,0,0,1,1
98,No Urgent Place,Friend(s),Sunny,55,Coffee House,2h,Male,21,Single,0,...,less1,1~3,less1,1~3,1,0,0,0,1,1
99,No Urgent Place,Friend(s),Sunny,55,Carry out & Take away,1d,Male,21,Single,0,...,less1,1~3,less1,1~3,1,1,0,0,1,1

In [ ]:
df.drop(columns=['car'], inplace=True)
df.tail(50)

,destination,passanger,weather,temperature,coupon,expiration,gender,age,maritalStatus,has_children,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Accept(Y/N?)
12634,No Urgent Place,Kid(s),Sunny,30,Restaurant(20-50),2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,0,0,0,1,0
12635,No Urgent Place,Kid(s),Snowy,30,Bar,1d,Female,26,Married partner,1,...,never,less1,less1,less1,1,0,0,0,1,0
12636,No Urgent Place,Kid(s),Sunny,55,Restaurant(<20),2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,0,0,1,0
12637,Home,Kid(s),Sunny,55,Restaurant(20-50),1d,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,0,1,0,0
12638,Home,Kid(s),Sunny,55,Restaurant(20-50),2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,0,0,1,0
12639,Home,Partner,Sunny,30,Bar,2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,1,0,1,0
12640,No Urgent Place,Kid(s),Sunny,30,Restaurant(20-50),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,0
12641,No Urgent Place,Kid(s),Snowy,30,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,0
12642,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12643,No Urgent Place,Friend(s),Sunny,80,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12644,No Urgent Place,Friend(s),Sunny,55,Bar,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,1
12645,No Urgent Place,Friend(s),Sunny,30,Carry out & Take away,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12646,No Urgent Place,Friend(s),Snowy,30,Restaurant(<20),1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12647,No Urgent Place,Alone,Rainy,55,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12648,No Urgent Place,Alone,Sunny,80,Restaurant(<20),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12649,No Urgent Place,Kid(s),Sunny,55,Restaurant(<20),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,1
12650,Home,Kid(s),Sunny,55,Restaurant(20-50),1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,1,0,0
12651,Home,Kid(s),Sunny,55,Restaurant(20-50),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12652,Home,Partner,Sunny,30,Bar,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,1,0,1,1
12653,Home,Alone,Sunny,80,Carry out & Take away,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,1,0,1
12654,Home,Alone,Sunny,30,Carry out & Take away,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12655,Home,Alone,Rainy,55,Coffee House,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12656,Home,Alone,Snowy,30,Coffee House,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12657,Home,Alone,Sunny,80,Restaurant(20-50),1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12658,Work,Alone,Rainy,55,Carry out & Take away,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12659,Work,Alone,Snowy,30,Coffee House,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12660,Work,Alone,Snowy,30,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,1,0,1,0
12661,Work,Alone,Sunny,80,Restaurant(20-50),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12662,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12663,No Urgent Place,Friend(s),Sunny,80,Bar,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12664,No Urgent Place,Friend(s),Sunny,55,Bar,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12665,No Urgent Place,Friend(s),Sunny,30,Carry out & Take away,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12666,No Urgent Place,Friend(s),Snowy,30,Restaurant(<20),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12667,No Urgent Place,Alone,Rainy,55,Bar,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12668,No Urgent Place,Alone,Sunny,80,Restaurant(<20),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12669,No Urgent Place,Partner,Sunny,30,Restaurant(20-50),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12670,No Urgent Place,Partner,Rainy,55,Bar,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12671,No Urgent Place,Partner,Snowy,30,Restaurant(<20),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12672,Home,Alone,Sunny,80,Carry out & Take away,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,1,0,0
12673,Home,Alone,Sunny,30,Carry out & Take away,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,0
12674,Home,Alone,Rainy,55,Coffee House,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,0
12675,Home,Alone,Snowy,30,Coffee House,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12676,Home,Alone,Sunny,80,Restaurant(20-50),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,1
12677,Home,Partner,Sunny,30,Restaurant(<20),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,1,0,1,1
12678,Home,Partner,Sunny,30,Restaurant(<20),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,1,0,0
12679,Home,Partner,Rainy,55,Carry out & Take away,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,1
12680,Work,Alone,Rainy,55,Carry out & Take away,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12681,Work,Alone,Snowy,30,Coffee House,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,0
12682,Work,Alone,Snowy,30,Bar,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,1,0,1,0
12683,Work,Alone,Sunny,80,Restaurant(20-50),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,0

In [ ]:
print(df.shape)

(12684, 24)

In [ ]:
fill_columns = ['Bar', 'CoffeeHouse', 'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50']
df[fill_columns] = df[fill_columns].fillna('never')
df.tail(50)

,destination,passanger,weather,temperature,coupon,expiration,gender,age,maritalStatus,has_children,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Accept(Y/N?)
12634,No Urgent Place,Kid(s),Sunny,30,Restaurant(20-50),2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,0,0,0,1,0
12635,No Urgent Place,Kid(s),Snowy,30,Bar,1d,Female,26,Married partner,1,...,never,less1,less1,less1,1,0,0,0,1,0
12636,No Urgent Place,Kid(s),Sunny,55,Restaurant(<20),2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,0,0,1,0
12637,Home,Kid(s),Sunny,55,Restaurant(20-50),1d,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,0,1,0,0
12638,Home,Kid(s),Sunny,55,Restaurant(20-50),2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,0,0,1,0
12639,Home,Partner,Sunny,30,Bar,2h,Female,26,Married partner,1,...,never,less1,less1,less1,1,1,1,0,1,0
12640,No Urgent Place,Kid(s),Sunny,30,Restaurant(20-50),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,0
12641,No Urgent Place,Kid(s),Snowy,30,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,0
12642,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12643,No Urgent Place,Friend(s),Sunny,80,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12644,No Urgent Place,Friend(s),Sunny,55,Bar,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,1
12645,No Urgent Place,Friend(s),Sunny,30,Carry out & Take away,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12646,No Urgent Place,Friend(s),Snowy,30,Restaurant(<20),1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12647,No Urgent Place,Alone,Rainy,55,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12648,No Urgent Place,Alone,Sunny,80,Restaurant(<20),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12649,No Urgent Place,Kid(s),Sunny,55,Restaurant(<20),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,1
12650,Home,Kid(s),Sunny,55,Restaurant(20-50),1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,1,0,0
12651,Home,Kid(s),Sunny,55,Restaurant(20-50),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12652,Home,Partner,Sunny,30,Bar,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,1,0,1,1
12653,Home,Alone,Sunny,80,Carry out & Take away,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,1,0,1
12654,Home,Alone,Sunny,30,Carry out & Take away,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12655,Home,Alone,Rainy,55,Coffee House,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12656,Home,Alone,Snowy,30,Coffee House,2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,0,0,1,0
12657,Home,Alone,Sunny,80,Restaurant(20-50),1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12658,Work,Alone,Rainy,55,Carry out & Take away,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,0,1,1
12659,Work,Alone,Snowy,30,Coffee House,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12660,Work,Alone,Snowy,30,Bar,1d,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,1,1,0,1,0
12661,Work,Alone,Sunny,80,Restaurant(20-50),2h,Male,31,Married partner,1,...,never,4~8,gt8,less1,1,0,0,1,0,0
12662,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12663,No Urgent Place,Friend(s),Sunny,80,Bar,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12664,No Urgent Place,Friend(s),Sunny,55,Bar,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12665,No Urgent Place,Friend(s),Sunny,30,Carry out & Take away,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12666,No Urgent Place,Friend(s),Snowy,30,Restaurant(<20),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12667,No Urgent Place,Alone,Rainy,55,Bar,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12668,No Urgent Place,Alone,Sunny,80,Restaurant(<20),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12669,No Urgent Place,Partner,Sunny,30,Restaurant(20-50),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12670,No Urgent Place,Partner,Rainy,55,Bar,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12671,No Urgent Place,Partner,Snowy,30,Restaurant(<20),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12672,Home,Alone,Sunny,80,Carry out & Take away,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,1,0,0
12673,Home,Alone,Sunny,30,Carry out & Take away,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,0
12674,Home,Alone,Rainy,55,Coffee House,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,0
12675,Home,Alone,Snowy,30,Coffee House,2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,0,1,0
12676,Home,Alone,Sunny,80,Restaurant(20-50),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,1
12677,Home,Partner,Sunny,30,Restaurant(<20),1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,1,0,1,1
12678,Home,Partner,Sunny,30,Restaurant(<20),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,0,1,0,0
12679,Home,Partner,Rainy,55,Carry out & Take away,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,1
12680,Work,Alone,Rainy,55,Carry out & Take away,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,0,1,1
12681,Work,Alone,Snowy,30,Coffee House,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,0
12682,Work,Alone,Snowy,30,Bar,1d,Male,26,Single,0,...,never,1~3,4~8,1~3,1,1,1,0,1,0
12683,Work,Alone,Sunny,80,Restaurant(20-50),2h,Male,26,Single,0,...,never,1~3,4~8,1~3,1,0,0,1,0,0

In [ ]:
categorical_columns = ['destination', 'passenger', 'weather', 'coupon', 'expiration', 'gender', 'age',
                       'maritalStatus', 'education', 'occupation', 'income', 'Bar', 'CoffeeHouse',
                       'CarryAway', 'RestaurantLessThan20', 'Restaurant20To50']
# Verify if all columns in categorical_columns exist in df
missing_columns = [col for col in categorical_columns if col not in df.columns]

if missing_columns:
    print(f"The following columns are missing in the DataFrame: {missing_columns}")
    # Either correct the column names in 'categorical_columns'
    # Or handle the missing columns in the DataFrame (e.g., add them if necessary)
else:
    df = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

The following columns are missing in the DataFrame: ['passenger']

In [ ]:
y = df['Accept(Y/N?)']
X = df.drop(columns=['Accept(Y/N?)'])
df.head(100)

,destination,passanger,weather,temperature,coupon,expiration,gender,age,maritalStatus,has_children,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Accept(Y/N?)
0,No Urgent Place,Alone,Sunny,55,Restaurant(<20),1d,Female,21,Unmarried partner,1,...,never,never,4~8,1~3,1,0,0,0,1,1
1,No Urgent Place,Friend(s),Sunny,80,Coffee House,2h,Female,21,Unmarried partner,1,...,never,never,4~8,1~3,1,0,0,0,1,0
2,No Urgent Place,Friend(s),Sunny,80,Carry out & Take away,2h,Female,21,Unmarried partner,1,...,never,never,4~8,1~3,1,1,0,0,1,1
3,No Urgent Place,Friend(s),Sunny,80,Coffee House,2h,Female,21,Unmarried partner,1,...,never,never,4~8,1~3,1,1,0,0,1,0
4,No Urgent Place,Friend(s),Sunny,80,Coffee House,1d,Female,21,Unmarried partner,1,...,never,never,4~8,1~3,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),1d,Male,21,Single,0,...,less1,1~3,less1,1~3,1,1,0,0,1,1
96,No Urgent Place,Friend(s),Sunny,80,Coffee House,2h,Male,21,Single,0,...,less1,1~3,less1,1~3,1,0,0,0,1,1
97,No Urgent Place,Friend(s),Sunny,80,Restaurant(<20),2h,Male,21,Single,0,...,less1,1~3,less1,1~3,1,1,0,0,1,1
98,No Urgent Place,Friend(s),Sunny,55,Coffee House,2h,Male,21,Single,0,...,less1,1~3,less1,1~3,1,0,0,0,1,1
99,No Urgent Place,Friend(s),Sunny,55,Carry out & Take away,1d,Male,21,Single,0,...,less1,1~3,less1,1~3,1,1,0,0,1,1

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [ ]:
y_pred = model.predict(X_test)

AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7446

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.66      0.69      1095
           1       0.76      0.81      0.78      1442

    accuracy                           0.74      2537
   macro avg       0.74      0.73      0.74      2537
weighted avg       0.74      0.74      0.74      2537


Confusion Matrix:
 [[ 718  377]
 [ 271 1171]]